COMPCERT_ARGS = [
    "-R",
    "lib",
    "compcert.lib",
    "-R",
    "common",
    "compcert.common",
    "-R",
    "x86_64",
    "compcert.x86_64",
    "-R",
    "x86",
    "compcert.x86",
    "-R",
    "backend",
    "compcert.backend",
    "-R",
    "cfrontend",
    "compcert.cfrontend",
    "-R",
    "driver",
    "compcert.driver",
    "-R",
    "export",
    "compcert.export",
    "-R",
    "cparser",
    "compcert.cparser",
    "-R",
    "flocq",
    "Flocq",
    "-R",
    "MenhirLib",
    "MenhirLib",
]

EXTLIB_ARGS = ["-Q", "theories", "ExtLib"]

FOURCOLOR_ARGS = ["-R", "theories", "fourcolor"]
